services:
  redis:
    image: redis:7-alpine
    container_name: bolt_procure_redis
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1"]
    ports:
      - "6379:6379"
    volumes:
      - procureos_redisdata:/data

volumes:
  procureos_redisdata:
